doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '14'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      AnswerEntity:
        type: annotation
        is_bundle: false
        prefix: App\Answer
        dir: '%kernel.project_dir%/src/Answer/'
      CardEntity:
        type: annotation
        is_bundle: false
        prefix: App\Card
        dir: '%kernel.project_dir%/src/Card/'
      DeckEntity:
        type: annotation
        is_bundle: false
        prefix: App\Deck
        dir: '%kernel.project_dir%/src/Deck/'

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
