# @format

version: '3.9' # optional since v1.27.0
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 5000:5000
    environment:
      POSTGRES_PASSWORD: postgres
    entrypoint: './init.sh'
  db:
    image: postgres:14.7
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
